### ISSUE TITLE
TODO's before queries can be used in the Discord bot

### ISSUE THREAD

**Issue by t1-tracey** [sky-music/sky-python-music-sheet-maker#109]
- [x] address TODOs listed in #104 

- [x] rewrite the methods from `responder.py` into `communicator.py`

- [x] rewrite the instructions. Maybe this should be done by parser??

- [x] write the music sheet maker's questions as queries, in the `create_queries()` method of `communicator.py`

- [x] make sure Parser works with queries 

- [x] determine if the use of asyncio is mandatory for the command line version to work

- [x] In music sheet maker, decide how to return the results of queries from one method to the overlapping one (the one which called this method), by returning Reply objects or directly doing Query.reply_to

- [x] check if the query_stock structure is adequate

- [x] address TODOs left in the code as comments

about the name 'Responder' or 'Communicator', any is fine. The problem is that Responder is not centred on communicating through Query messages.

The communicator/responder is what's between Parser and the outside. Right now, I feel that the current Responder class is still way too structured for only the command line — all of the `Responder.ask_to_select_mode()` `ask_song_key` `def ask_song_headers` etc. methods need to be written as each queries now

**Comment by t1-tracey** [comment]
I’ll work on this but I can’t make any promises about how fast. I will probably be unlikely to be able to work on it this weekend for example :(

**Comment by jmmelko** [comment]
Ok.
I would have liked to help, but you lost me after creating music_sheet_maker, it’s too much embedding for me!
That-Sky-Bot->Music_Cog->MusicSheetMaker->Communicator->Query

If I understand well, MusicSheetMaker will do what Responder did?
And the old code of Responder will disappear, or maybe be recycled in command_line?

**Comment by t1-tracey** [comment]
Oh sorry it must be confusing 😓 the old code for Responder will go into Communicator. 

As for the Song, Parser objects, right now they are properties of Responder (self.song, self.parser). I feel like they didn’t belong to responder/communicator specifically. So the Music Sheet Maker will have those properties instead:

```
class MusicSheetMaker:
   self.parser
   self.communicator
   self.song
```
etc.

As for the communication between the bot and our program, oh fundamentally it’s this:

Music Cog <-> Sky Python Music Sheet Maker

Inside That-Sky-Bot, there is a sub folder with the whole sky-python-music-sheet-maker in it

**Comment by jmmelko** [comment]
Okay so we can consider that music cog will be Alex’s responsibility in time.
And that the “refactoring before production” he has been talking about would apply to the Cog. But not to the Maker.

**Comment by jmmelko** [comment]
Ok, so, to resume:

* communication.py is a low-level *module* for classes such as Query, Reply, and QueryMemory
* communicator is a personae, the only one allowed to manipulate objects in communication.py. It will create Queries based on what is required by Sky Sheet Music Maker. For instance it will use .yaml files.
* Sky Sheet Music Maker is our program as a whole: it will create Songs, call Renderer, Parser, etc
* Music Cog is the cog within that-sky-bot

We can consider that music cog will ultimately be Alex’s responsibility.
And that the “refactoring before production” he talked about would apply to the Cog. But not to the Maker.

**Comment by jmmelko** [comment]
Something like that:

![B6791330-8ACE-43B9-AA73-34FD4C607CF4](https://user-images.githubusercontent.com/17069038/74939647-8b25fb00-53f0-11ea-9872-77c6a948938a.jpeg)

**Comment by jmmelko** [comment]
Implying that:

* the bot will *not* see Communicator, only the Maker
* starting from an order from the bot (“create a song”), the Communicator will create the appropriate Queries (“what are the instructions for this? Which musical formats are supported?”),  to which the Maker will try to Reply. Conversely, the Communicator will issue Queries (“what are the notes?”, “what is your notation?”), that the Maker will transmit back to the bot, waiting for an answer from the player.

So... while on one hand we know which questions the Maker can ask the player, on the other we have to list all the possible questions the player can ask the Maker.
Each of these questions will give rise to a specific method, in which one or several Queries are created and stored in the brain.

For questions that are not anticipated, we have 2 solutions:
* do nothing (raise an error or send back a generic “I don’t understand” message)
* try to guess what is meant, ie scan the question text for keywords and try to find the appropriate method. The problem is that this task is specifically the bot’s job. So I would advise against doing it. The bot/cog are supposed to send straight, explicit orders, ie call functions by their names. All the pseudo-intelligence (ie conversational abilities)  is supposed to be managed by the bot.

**Comment by jmmelko** [comment]
Alternate solution:

![285AD456-ED31-43C4-A713-BA70DEB5304C](https://user-images.githubusercontent.com/17069038/75027229-799b2c80-549e-11ea-964b-84062d8d4d48.jpeg)

**Comment by t1-tracey** [comment]
Ohh initially I intended for communicator to be between Maker and the Bot, like your second digram and in this description^^

> Another solution, which contradicts my drawing, would be to force the bot/cog to use the Query/Reply structure directly. This is what I intended in the first place. Either by forcing it to instantiate Query and Reply directly from the communication module, or by instantiating it’s own Communicator, who will handle queries.

Hehe you drew pictures to visualise it~ I like that.

**Comment by t1-tracey** [comment]
Ah wait I’m confused too...

About Alex being in charge of the Music Cog, I think that’s fair and that’s what he intended too actually ^^ before I tried the prototype to test it. The thing is, we will need to provide very clear and concise documentation. On how to start a song, parse notes, pass on questions about key etc. (which is being done through queries now)

I’m not going to just leave the burden to you btw – I intend to stay on this project, I just can’t work on it as often 😭

**Comment by t1-tracey** [comment]
Hm I guess I just feel guilty about not being able to work on this. 

I did my own version of diagram:


![IMG_3406](https://user-images.githubusercontent.com/22441348/75029541-51d7b300-54f6-11ea-8829-5eb2b926fc3f.png)

![IMG_3407](https://user-images.githubusercontent.com/22441348/75029546-5603d080-54f6-11ea-9fea-6b86a59335ec.png)

**Comment by jmmelko** [comment]
> Hm I guess I just feel guilty about not being able to work on this.
> 
> I did my own version of diagram:
> 

That’s great because I started to write down a few lines of code and I naturally converged to the first solution, and then I realized that it would be silly to invent such an elaborate communication system if it were to use it internally.

**Comment by jmmelko** [comment]
I think that communicator could be on the Maker side only, as a shortcut to generate queries.
We can suppose that the bot/cog is a natural communicator handling queries natively

**Comment by jmmelko** [comment]
mmmhhh... 
I took a look at your music cog again and I wonder if I didn’t pushed things too far by my lack of knowledge. Everything is in it already.

For instance: song = await Questions.ask_text(self.bot, channel, ctx.author....

is nothing more than our Query() object!

And: await channel.send(

is nothing more than Information()!

And:

await channel.send(files=my_files)

looks like a Reply!

So the only thing to do is to feed these asynchronous routines (utils.Question, channel.send) content from our Query, Reply, and Information objects.

**Comment by jmmelko** [comment]
![F375346C-4646-4D46-9CD7-532194B1AFC6](https://user-images.githubusercontent.com/17069038/75088978-4adf8d80-5554-11ea-9796-f4fcb3c6e007.jpeg)

**Comment by t1-tracey** [comment]
Ahhh yes this is what I had in mind too!!

**Comment by t1-tracey** [comment]
Oh I’m not sure, just logged onto website now to see comment (saw picture from email). Yeah I don’t know how to implement it, that was the system I had in mind though :D

Haha I will focus on school project for now as you said, one document is approaching finished state now - but I do enjoy working on side projects though.

**Comment by t1-tracey** [comment]
Ok I think we are able to write a communicator class for the bot too (It's possible to make classes at the top of the Music Cog) so 2 communicator classes is possible

**Comment by t1-tracey** [comment]
I'm going to get back to working on this next weekend, as a heads up 👍

**Comment by jmmelko** [comment]
> I'm going to get back to working on this next weekend, as a heads up 👍

Great !

Maybe should we organize a live chat so I can better answer your question on how things work so far. I am available between 7:00 and 9:00 GMT on weekdays, and between 7:00 and 18:00 GMT on weekends.

There are two things that bother me very much:

1/ I have the feeling that what we have created is too complex. I am starting to wonder if what Alex meant by “make the question a model” was not simply the equivalent of utils.Question.
But the guy is very conceptual in the way he talks, hasn’t been very directive, and hasn’t been very clear about whether it was mandatory to make the change before we can push the Cog.

2/ the conversation (ie exchange of Queries) between bot and maker is artificial so far, since I am doing tests on a command line program. Not only both parties are on the same machine, but it is entirely sequential. Meaning that each party, after creating a Query (Query.send()), must call a method in the other party communicator (maker.communicator.receive) to force it to read the Query.

The only other way to do that would be to use asynchronous programming (asyncio module). In which one party would sequentially emit queries, and store them on a global variable (let’s call it the mailbox), while the other party would periodically check the mailbox from time to time. And vice-versa.

We could do that on the same machine, but I took a look at asyncio and was a bit afraid.

Finally, all of these would make much more sense if there the asynchronous communication took place between distant machines, between server (discord/bot/music-cog) and client (player/discord).

**Comment by t1-tracey** [comment]
Oh yes! How about a live chat on discord? I will be available on one of the weekend days. Hm ok 6am GMT is currently 5 pm here, how about 9am GMT on Saturday?

I see about asyncio, I’ve never used it outside this before (my first encounter was in the music cog) it seemed frightening to me too haha^^

> The only other way around would be to use asynchronous programming (asyncio module). In this case, one party would sequentially emit queries, and store them inside a shared global variable, or maybe inside the other party. Let’s call this variable the mailbox. In the meantime, independently, the other party would periodically check its mailbox from time to time. And vice-versa.

 I understand this description though!

**Comment by jmmelko** [comment]
> Oh yes! How about a live chat on discord? I will be available on one of the weekend days. Hm ok 6am GMT is currently 5 pm here, how about 9am GMT on Saturday?

Ok, I’ll send you a message the day before to confirm.

**Comment by t1-tracey** [comment]
Sure^^ 👍 it’s live text chat, to confirm?

**Comment by jmmelko** [comment]
> Sure^^ 👍 it’s live text chat, to confirm?

Yes, we could use the chat channel of your discord Sky Music Maker account, or another temporary channel.
Discord is more or less live, isn’t it?
We could invite Strawb also, I wonder why she hasn’t given any news recently

**Comment by jmmelko** [comment]
That’s ok for 9:00 GMT = 10:00 Paris = 20:00 Melbourne.
(We can still shift by +/- 1h if you want, in this case tell me asap)

**Comment by t1-tracey** [comment]
Yep any channel is fine, sorry I didn’t get to respond yet^^
And 20:00 Melbourne is ok with me 👍

**Comment by jmmelko** [comment]
It was nice talking to you. Sorry I talked too much but I felt the need to report to you on what I did.

In the meantime I have added a working script using asyncio. It does not use our program yet.

**Comment by t1-tracey** [comment]
No worries 😊 yeah it must have been hard working on it for two weeks without being able to report to me 😓 I enjoyed chatting too.

Ok, I’m hoping to get to know the changes better today, going to run the puppet MusicSheetMaker and CommandLinePlayer

**Comment by t1-tracey** [comment]
ok I managed to run through CommandLinePlayer and MusicSheetMaker, and I think I'm starting to understand the changes better now^^
once we are clearer on how to use asyncio, I'd like to help with creating the questions.

some of the questions, such as `ask for input mode`, rely on information *after* Parser has parsed the notes from the user

**Comment by jmmelko** [comment]
> once we are clearer on how to use asyncio, I'd like to help with creating the questions.

Actually we could use asyncio without changing anything else, just by adding the async keyword before definitions and the await command before calls 😝. People sometimes do that to speed up execution (independent tasks are run concurrently) , but in our case we don’t have any time issue related to queries.

So, the real question behind asyncio the question will be to use a mailbox concept instead of a puppet concept. I mean, instead of having two puppets pulling strings from each other (receive(), execute_queries()), they would be periodically checking their inbox for new messages to process.

I have asked info to Alex about the urge to use asyncio.

> some of the questions, such as `ask for input mode`, rely on information _after_ Parser has parsed the notes from the user

Yes.
We *could* arrange for these questions to be answered before *or* after parsing though. (if answered_before then dont_ask).

**Comment by t1-tracey** [comment]
Ah okay, I see

Oh yeah but the input modes and song key need to be asked *after* parsing, e.g. — 

```
Choose song key from A, D, E
```
A, D, E are calculated from the possible keys method determined by Parser.

```
Multiple possible input modes detected:
1) Sky keyboard
2) English notation
Choose input mode: (1-2)
```

The two options were determined by Parser, after the user has pasted the notes.
