### ISSUE TITLE
Todo's for WesternParser

### ISSUE THREAD

**Issue by t1-tracey** [sky-music/sky-python-music-sheet-maker#35]
- [x]  I wasn't sure where to put the methods that are currently in WesternParser i.e. should I make another class, or put them all into the one Parser class? I made a separate WesternParser class for now

- [x]  there are some regexps that I would like to be compiled first, and I hadn't gotten around to looking that up

- [x]  still need to implement `find_keys` to detect a key automatically, and haven't replaced the `map_note_to_position` with `calculate_coordinate_for_western_note` yet

**Comment by jmmelko** [comment]
You know what, that’s exactly what I was thinking: “now we need to do some
clean-up”.

I think that’s perfectly fine to create a separate class, provided the following:

* the class is not directly instanced from main. I think we should call a generic parser and then this parser calls the western parser if necessary
* we should not duplicate functions (at least, not long ones), otherwise the code will be more difficult to maintain.
* we have to think about other notations: Jianpu, and doremifasol.

=> the key to satisfy those is to realize that WesternParser is a *note* parser, not a song parser.

What we can try is the following:
* keep the current Parser class
* define different note parsers (Western, Jianpu, etc), possibly inheriting some basic functions from each other. Another solution is to define a unique WesternParser, but put the “Jianpu”, “Western”, “doremi” notation as input in the init()
* run the detect_input method to determine the notation
* instantiate the right note parser for the selected notation

def Parser():
    def __init__():
    note_parser = None

    def parse_lines():
        mode = self.detect_input_type(song_lines)
        if mode == InputMode.WESTERN:
             self.note_parser = WesternParser()
.....
      def parse_chords():
            .....
            self.note_parser.map_note_to_position(note)
         

to handle Jianpu and dorémi, you should put the RegExp  r'[ABCDEFGabcdefg][b#]?\d',  as a property of WesternParser, not in the methods

**Comment by t1-tracey** [comment]
I have implemented putting the regex as a property of the class now :D

**Comment by t1-tracey** [comment]
Ok I managed to define a generic NoteParser now (didn't expect it to be quite straightforward) :joy:

the work is in the western-scales branch, my memory of inheritance in python is a bit rusty so feel free to clean up anything.

I am going to be away soon, so I will take a break from working on this, don't feel pressured to work while I am away ^^

**Comment by t1-tracey** [comment]
😍 I managed to transcribe a song in another scale!!!

```
# threshold

# first part
F#1A1C#1F#2 G#1 F#1A1C#1 E2-F#2-G#2
E1G#1B1E2A2 B1 F#1A1C#1 G#2
F#1B1D#1F#2B2 A1 E1G#1B1 C#2 E1 G#2
E1A1C#1G#2 E1A1C#1A2
# second part
F#1A1C#1F#2 F#1-G#1 F#1A1C#1 E2-G#1F#2-G#2
E1B1F#2A2 E2B2 E1A1C#1D#2
F#1B1D#1F#2B2 E3 E3 G#1C#1E2G#2D#2 G#2C#2
A2 B2
A2-G#2 A2-G#2 G#2 B2-A2 A2-G#2
```

there were some issues with ascii output, but I disabled that for now, png and html work though

![Threshold](https://user-images.githubusercontent.com/22441348/69780061-45e19b00-11fe-11ea-9fb5-73aed42aea85.png)
![Threshold1](https://user-images.githubusercontent.com/22441348/69780062-45e19b00-11fe-11ea-9bec-8d8b13c8a90f.png)
![Threshold2](https://user-images.githubusercontent.com/22441348/69780063-467a3180-11fe-11ea-80b1-faf38d055e23.png)

here was the temporary hack that I did to change it (the key I wanted was E major, so that's why I put 'E')
![Screen Shot 2019-11-28 at 4 40 58 pm](https://user-images.githubusercontent.com/22441348/69780083-572aa780-11fe-11ea-84cf-29d2a169fa24.png)

**Comment by jmmelko** [comment]
Great!

I’ll take a look. Yep, That’s the magic of object-oriented programming.
I think that the original parser will be renamed song text parser, and that everything related to Sky notation be moved in a Sky specific (=musical-key-less) note parser.

I don’t feel pressured, but some people should (Alex, ahem, cough cough, do you hear me?)

**Comment by t1-tracey** [comment]
Haha i guess he is a teacher so maybe is busy

I managed to replace `map_note_to_position` with `calculate_coordinate_for_note` now!

your previous `find_key` method has worked so far on my songs hehe, feel free to replace with the new `find_western_key` method if you like too

**Comment by jmmelko** [comment]
Great job really.
Have you finished with the WesternParser?

Do you want me to implement Jianpu and doremi notations? Or take a look at the code structure? (look out for unnecessary method definitions, or lacking ones, such as the set_ and get_ functions, etc)

Before you leave could you please leave a todo list? I think I will tackle the support for Asian characters first.

**Comment by t1-tracey** [comment]
Thanks hehe.

Yeah I finished setting up the WesternParser now.

Ok sure, I'll write up

On 29 Nov 2019, at 5:28 pm, jmmelko <notifications@github.com> wrote:

﻿Great job really.
Have you finished with the WesternParser?

Do you want me to implement Jianpu and doremi notations? Or take a look at the code structure? (look out for unnecessary method definitions, or lacking ones, such as the set_ and get_ functions, etc)

Before you leave could you please leave a todo list? I think I will tackle the support for Asian characters first.
